### ISSUE TITLE
html

### ISSUE THREAD

**Issue by appt2** [CaiMuCheng/WebDevOps#3]
Hello, please provide grammar and support files in html when opening and closing the style tag to display css codes like vscode

**Comment by CaiMuCheng** [comment]
This project will no longer be maintained, and now this project has been refactored into Leaf IDE.

**Comment by appt2** [comment]
> This project will no longer be maintained, and now this project has been refactored into Leaf IDE.

Well, have you used Lexer in the project you mentioned?

**Comment by CaiMuCheng** [comment]
Not yet, this project is still under development

**Comment by appt2** [comment]
> Not yet, this project is still under development

Well, when do you use it? I tested your program. I couldn't enter the code editor. If you use special grammars, add the g4 file as well.

**Comment by CaiMuCheng** [comment]
I will use JFlex instead.Antlr parsing is slow

**Comment by appt2** [comment]
> I will use JFlex instead.Antlr parsing is slow

Isn't JFlex obsolete?

**Comment by CaiMuCheng** [comment]
Then I'll write it myself. In fact, I wrote the JSON parsing for WebDevOps myself.

**Comment by appt2** [comment]
> Then I'll write it myself. In fact, I wrote the JSON parsing for WebDevOps myself.

It's great, you can send the link because g4 grammar is difficult
